name: brew livecheck

on:
  schedule:
    # Every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: jonchang

      - name: Fix Homebrew version
        run: git -C $(brew --repo) reset --hard cb72872c83686ea1450d818c8ac8902c38a05bb8

      - name: Bump
        id: update
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.TOKEN }}
          TOKEN: ${{secrets.TOKEN}}
          LIVECHECK: true
          TAP: jonchang/tap
          FORMULA: kolmafia
          HOMEBREW_NO_ENV_FILTERING: 1
        run: |
          git fetch origin
          BRANCH="update"
          echo "::set-output name=branch::${BRANCH}"
          if git ls-remote --exit-code --heads origin "$BRANCH"; then
            git checkout "$BRANCH"
            git reset origin/main
          else
            git checkout -B "$BRANCH" origin/main
            BRANCH_EXISTS="1"
          fi
          if brew ruby ./.github/actions/bump.rb; then
            git add "$GITHUB_WORKSPACE/Formula/*.rb"
            git commit -m "update"
            echo "::set-output name=committed::true"
            if [ -n "$BRANCH_EXISTS" ]; then
              echo "::set-output name=pull_request::true"
            fi
          fi
      - name: Push commits
        if: steps.update.outputs.committed == 'true'
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ secrets.TOKEN }}
          branch: ${{ steps.update.outputs.branch }}
          force: true

      - name: Open a pull request
        if: steps.update.outputs.pull_request == 'true'
        run: hub pull-request --no-edit
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
